install:
 - mvn -B clean; java -version
script:
 - travis_wait 60 mvn -B -Ptravis,jboss-repository -fae -Dserver.version=$SERVER_VERSION ${ELYTRON:+-Delytron} install; cat /home/travis/build/rsearls/Resteasy/server-adapters/resteasy-vertx/target/surefire-reports/org.jboss.resteasy.test.asyncio.SSETest-output.txt;

language: java
jdk:
  - openjdk8
  - openjdk11
env:
  - SERVER_VERSION=18.0.1.Final
  - SERVER_VERSION=19.0.0.Beta2
  - SERVER_VERSION=19.0.0.Beta2 ELYTRON=true
jobs:
  exclude:
    - jdk: openjdk11
      env: SERVER_VERSION=19.0.0.Beta2 ELYTRON=true
  include:
    - stage: "javadoc"
      script: mvn -B -Pjboss-repository -DskipTests install && mvn -B -Dmaven.javadoc.skip=false javadoc:javadoc
      jdk: openjdk8
      env: SERVER_VERSION=19.0.0.Beta2
    - stage: "javadoc"
      script: mvn -B -Pjboss-repository -DskipTests install && mvn -B -Dmaven.javadoc.skip=false javadoc:javadoc
      jdk: openjdk11
      env: SERVER_VERSION=19.0.0.Beta2
addons:
  hosts:
    - localhost.localdomain
##cache:
# directories:
#  - $HOME/.m2
